# ── Profil PROD — PostgreSQL ─────────────────────────────────────────────────
# Activation : -Dspring.profiles.active=prod
# ou variable d'environnement : SPRING_PROFILES_ACTIVE=prod

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskmanager}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:app}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:secret}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# H2 console désactivée en prod
spring.h2.console.enabled=false
